### ISSUE TITLE
Support pagination

### ISSUE THREAD

**Issue by DannyFeliz** [bvaughn/js-search#10]
It would be great if this library supports pagination because I have a lot of results and I wanna paginate it like this http://botmonster.com/jquery-bootpag/#example-advanced

Thanks!

**Comment by bvaughn** [comment]
I'm not sure what it would mean for a search library to support pagination. Could you elaborate?

Seems to me like you could paginate the results given you by `js-search` when you display them. (This library doesn't display any data after all, just indexes and searches it.)

**Comment by DannyFeliz** [comment]
You are completely right about everything you said, the pagination is not responsibility of `js-search`, sorry. Thank you very much for answering.

**Comment by bvaughn** [comment]
No problem at all. Glad you're finding the library useful!
