### ISSUE TITLE
Add multiple language support to SimpleTokenizer

### ISSUE THREAD

**Issue by rtkhanas** [bvaughn/js-search#11]
`text.split(/[^a-zA-Z0-9\-']+/)` works only for Latin, what about making it more advanced and support other(Cyrillic, Korean, Japanese etc.) as-well?

**Comment by bvaughn** [comment]
Hey @rtkhanas,

The docs make mention of this under the header [tokenization](https://github.com/bvaughn/js-search#tokenization). Tokenizing some Asian languages is more difficult and so I left it for user land.

If you would like to contribute an implementation, I'd be happy to add it as another option to the library! :)

I don't plan to create a non-Latin tokenizer myself though so I'm going to close this issue. We can continue to chat here if you'd like to talk about ideas for creating one. :)
