### ISSUE TITLE
Strange behavior on IE<11

### ISSUE THREAD

**Issue by JacobEvelyn** [bvaughn/js-search#12]
I've noticed that I sometimes don't see `js-search` results that match part of a word in older versions of IE (before IE11). For example, here's the latest Safari:

![safari-js-search](https://cloud.githubusercontent.com/assets/1114569/18218875/90852934-7133-11e6-9a38-e0b4458374e1.gif)

And here's the same thing in IE10:

![ie10-js-search](https://cloud.githubusercontent.com/assets/1114569/18218890/a5b8f682-7133-11e6-8fba-ff6d39f8b786.gif)

I can't seem to figure out what's causing _some_ of the results to appear in IE (doesn't appear to be related to capitalization or the location of the match within the string) but not others. Any guidance here would be much appreciated.

**Comment by JacobEvelyn** [comment]
Sorry about the gif quality; here's a closer look at the number of results.

Safari:

![safari-js-search-close](https://cloud.githubusercontent.com/assets/1114569/18219006/6d30200a-7134-11e6-9874-a7dfca0c0419.gif)

IE10:

![ie10-js-search-close](https://cloud.githubusercontent.com/assets/1114569/18219011/75b06000-7134-11e6-988c-1f0c68d0a281.gif)

**Comment by bvaughn** [comment]
Hey @JacobEvelyn.

Sorry for the slow response! I'm traveling in China atm and my Internet access is spotty.

Thanks for the quality bug report. Greatly appreciate the detail.

I have no idea what's going on here to be honest. I am able to reproduce the issue though using a VM with IE 10.

**Comment by bvaughn** [comment]
I am able to reproduce this with a reduced book set:
```json
{
  "books": [
    {
      "isbn": "0877854106",
      "title": "A Swedenborg Sampler: Selections from Heaven and Hell, Divine Love and Wisdom, Divine Providence, True Christianity, and Secrets of Heaven",
      "author": "Emanuel Swedenborg"
    },
    {
      "isbn": "0520203259",
      "title": "Hellenistic history and culture",
      "author": "Peter Green"
    },
    {
      "isbn": "0521228298",
      "title": "The Hellenistic world from Alexander to the Roman conquest : a selection of ancient sources in transla",
      "author": "M. M Austin"
    },
    {
      "isbn": "0521306965",
      "title": "A Hellenistic anthology",
      "author": "Neil Hopkinson"
    }
  ]
}
```
For some reason, IE10 shows the following results:

Search text | Num results
:---|:---
h | 4
he | 0
hel | 0
hell | 1

Chrome behaves as would be expected.

**Comment by bvaughn** [comment]
Ah! Found the issue, although I'm not sure I understand it.

I was tokenizing like so:
```js
public expandToken(token:string):Array<string> {
  var expandedTokens = [];
  var prefixString:string = '';

  for (var i = 0, length = token.length; i < length; ++i) {
    prefixString += token.charAt(i);
    expandedTokens.push(prefixString);
  }

  return expandedTokens;
}
```

But for some reason, IE10 would sometimes turn a token like "foobar" into "f, foobar, foobar, foobar, foobar, foobar" (instead of "f, fo, foo, foob, fooba, foobar"). I was able to fix this by changing the tokenizer to use `.substr` instead of appending to the string:

```js
public expandToken(token:string):Array<string> {
  var expandedTokens = [];
  var prefixString:string = '';

  for (var i = 0, length = token.length; i < length; ++i) {
    expandedTokens.push(token.substr(0, i + 1));
  }

  return expandedTokens;
}
```

**Comment by bvaughn** [comment]
Fixed via 2f496b3, released as version 1.3.2. Thanks for the report.

**Comment by JacobEvelyn** [comment]
Thanks so much for the speedy investigation and fix!

**Comment by NiallRobson** [comment]
Hi @bvaughn,
This bug was reintroduced with https://github.com/bvaughn/js-search/commit/201d73246e33f2d881818cfdca83230f74b1a86a

**Comment by bvaughn** [comment]
PRs welcome. I won't have time to look into this.
