### ISSUE TITLE
How can I search for the whole words?

### ISSUE THREAD

**Issue by phkavitha** [bvaughn/js-search#14]
If I've a JSON array of the format:
````js
[
 {
    key1: 'text 1',
  },

 {
    key1: 'text 12'
  }
]
````

If I search for "text 1", then I should get only one JSON object as result.

**Comment by bvaughn** [comment]
By [default](https://github.com/bvaughn/js-search/blob/798cd8a1f959acbdd28654ea85eb6a961590b17e/source/search.ts#L42), js-search uses the [`AllSubstringsIndexStrategy`](https://github.com/bvaughn/js-search/blob/master/source/index-strategy/all-substrings-index-strategy.ts) which matches all substrings. That means "te" would match "text 1" and "text 12" in your example above.

Check out the [index strategies](https://github.com/bvaughn/js-search/tree/master/source/index-strategy). Sounds like you want the [`ExactWordIndexStrategy`](https://github.com/bvaughn/js-search/blob/master/source/index-strategy/exact-word-index-strategy.ts) instead.

```js
var search = new JsSearch.Search('your-id');
search. indexStrategy = new JsSearch.ExactWordIndexStrategy();
// Add your documents here
```
