### ISSUE TITLE
How is indexing/search performance on large corpus of documents?

### ISSUE THREAD

**Issue by KyleAMathews** [bvaughn/js-search#16]
E.g. a blog or documentation site?

Would it be possible perhaps to pre-index content at build time? If indexing is a bottleneck, then this could significantly help on slower devices e.g. old phones. Though perhaps just use the web-worker version.

**Comment by bvaughn** [comment]
That's a good question. I have used this lib and [js-worker-search](https://github.com/bvaughn/js-worker-search) on corpuses of many documents, each containing a sentence or two of text (eg things like name, address, etc) but I haven't used either yet on corpuses with documents containing large amounts of text (eg blog posts).

I have thought a bit (but not much) about the idea of pre-built indexes. I've actually thought on it from the angle or persisting an index and then restoring it later. But I haven't had the time to really put much thought or effort into either. In general, I'm a fan of the idea.

The tricky part would be that some functionality (eg TF-IDF ranking) is coupled to the index implementation and so to pre-build it would require coupling with the implementation. This is why persisting an existing index is preferable (although you'd have to handle things like backwards incompatible upgrades).

Any chance you'd be interested in helping? 😄

**Comment by KyleAMathews** [comment]
Possibly! I really want to have docs sites built with Gatsby work completely offline so having search be handled locally (not with Algolia) is pretty compelling. I'll have to give this a go when I have a chance — I've used Lunr with ~2500 longish documents (journal entries) and while indexing takes a decent bit of time ~5-10 seconds, searches are quite quick.

This is something I'll be giving a lot of time in the near future but will be poking around hopefully soon!

**Comment by bvaughn** [comment]
Oooh...well, I've perf-measured this lib against Lunr and- last I checked- js-search was faster. js-worker-search is the same basic algorithm, but trimmed a bit further _and_ moved to a web worker- so I think you'll find its performance even better. (I've built indexes of several tens of thousands of user/table/account objects with it before and didn't even notice a tiny hiccup, but again, these are different kinds of data.)

I would be interested in collaborating on the ability to persist-and-restore (and so pre-generate) these indexes. I'm a bit swamped for time at the moment though, with the new job _and_ looking to move. But... maybe things will clear up a bit over the holidays. :)

**Comment by bvaughn** [comment]
Thinking a little more about this, I believe the way I would approach this would be to augment `ISearchIndex` with 2 additional methods: `persist` and `restore`. `persist` would return a representation of the index that could be stored somewhere (eg cookie, localStorage, on a server, whatever) and then `restore` would accept, as a parameter, that same object.

There's some potential trickiness here:
* Detecting/handling version changes (eg data persisted with version X of js-search and later restored with version X+1).
* Tokenizer and sanitizers pre-process the search data to help build an index. They also pre-process search terms to ensure they can be matched to the index in a reasonable way (eg if you lowercase your search documents you probably also want to lowercase your search terms- so the end result is case insensitive search). It's possible to _persist_ data that was sanitized and tokenized one way and then to later restore it into an instance of js-search configured to sanitize/tokenize another way. I'm not sure if we'd want to guard against this or just warn via documentation. If we wanted to guard against it, we may actually need to move the `persist` and `restore` methods up to the top-level search object itself- essentially requiring it to take a snapshot of which tokenizers/sanitizers/index-strategies it was using. However this is tricky in the case of custom/user implementations. (How do I restore an implementation I don't know about?)

**Comment by bvaughn** [comment]
For discussion purposes: https://github.com/bvaughn/js-search/pull/17

**Comment by bvaughn** [comment]
Interesting to note that using `JSON.stringify` and `JSON.parse` to restore the index takes significantly longer than just rebuilding the index- at least with my initial tests. It's over 2x slower for `TfIdfSearchIndex` and a bit less than 2x slower for `UnorderedSearchIndex`.

**Comment by KyleAMathews** [comment]
Huh that is interesting. Perhaps this is just premature optimization on my
part :-)

**Comment by bvaughn** [comment]
I think using web workers is probably a more promising route for addressing performance concerns 😁 I'm going to close this issue for now as I don't think I plan any further action currently. Happy to discuss it more though!
