### ISSUE TITLE
Apostrophe breaks search

### ISSUE THREAD

**Issue by dangnelson** [bvaughn/js-search#19]
Searching for a string with an apostrophe like "Driver's" breaks the search and causes no results to be returned even though there are titles with that string.

**Comment by dangnelson** [comment]
This had to do with the fact that the string was using a specials character apostrophe instead of the standard typed one.

**Comment by bvaughn** [comment]
Great! Glad to hear it was something simple. 😄

If it's important, you could guard against this with a custom sanitizer (that converted all apostrophe-like characters to the same exact character)
