### ISSUE TITLE
[Urgent] Build is broken

### ISSUE THREAD

**Issue by bbenezech** [bvaughn/js-search#22]
Weird tooling issue or (hopefully) copy/pasting misstep:
https://github.com/bvaughn/js-search/blob/master/dist/js-search.js#L595

**Comment by bvaughn** [comment]
Hm. Looks like my build tooling didn't properly handle the recent pull request #21

**Comment by bvaughn** [comment]
Try version 1.3.5.

Looks like Fly concat stopped working (for reasons unknown) so I had to shuffle the build process slightly.

Thanks for the report.

**Comment by bbenezech** [comment]
Thanks!
