### ISSUE TITLE
Can I change the indexStrategy based upon the search query?

### ISSUE THREAD

**Issue by phkavitha** [bvaughn/js-search#27]
My requirement is to change the indexStrategy based upon the search query. In the app, if I search for say -100, then the search results should give me only the rows containing -100 and not 100.  However, for all other search queries, it should do a substring matching. Is there any way to achieve it?

**Comment by bvaughn** [comment]
Changing the index strategy requires re-building the index. Alternately you could maintain 2 search (pre-built) indexes that you choose between so you don't end up JIT re-building the index over and over again (which would be bad for performance).

TBH I don't understand why a single index wouldn't work based on your previous description. Searching "-100" and expecting it to only return rows containing "-100" and not "100" is also a substring match. 😄
