### ISSUE TITLE
Sorting the results

### ISSUE THREAD

**Issue by anshul2209** [bvaughn/js-search#28]
First of all thanks for the awesome module.@bvaughn
My use case is If I search for bird , the results should be such that 'birdman' is diplayed first then 'angry bird' or when I press 'a' the result should be sorted to have all the words starting from 'a' first and then other matching words. I am not sure how do I achieve that .

**Comment by bvaughn** [comment]
Thank you. 😄 

If you want the results returned by js-search to be in this order- take a look at the [`SearchIndex` interface](https://github.com/bvaughn/js-search/blob/master/source/SearchIndex/SearchIndex.js. By default this library only provides an [unordered index](https://github.com/bvaughn/js-search/blob/master/source/SearchIndex/UnorderedSearchIndex.js) and a [tf-idf ordered index](https://github.com/bvaughn/js-search/blob/master/source/SearchIndex/TfIdfSearchIndex.js). What you're describing could be accomplished by creating a new index strategy type.

Depending on the number of results, you may find it easier to sort the result of an unordered index. I don't know how this would perform- potentially poorly, if you have a lot of results. You would have to experiment and see. 😄 

Unfortunately what you've described isn't supported out of the box.
