### ISSUE TITLE
Custom weighting of results depending on field

### ISSUE THREAD

**Issue by meltuhamy** [bvaughn/js-search#30]
Imagine I have 2 documents which have multiple indexed fields like `{title: 'Hello', description: 'Something'}` and  `{title: 'World', description: 'Hello'}` 

Is it possible to be able to specify that the `title` field is more important than the description field? In other words, if I search for `hello`, I expect `{title: 'Hello', description: 'Something'}` to come first?

**Comment by bvaughn** [comment]
Not without implementing your own `SearchIndex`. Default is [unordered/unweighted](https://github.com/bvaughn/js-search/blob/master/source/SearchIndex/UnorderedSearchIndex.js). A [TF-IDF (ranked) implementation](https://github.com/bvaughn/js-search/blob/master/source/SearchIndex/TfIdfSearchIndex.js) is also provided.
