### ISSUE TITLE
How to add a SearchIndex that is a deep key

### ISSUE THREAD

**Issue by DannyFeliz** [bvaughn/js-search#32]
Hey man this library is awesome :tada: 

I was wondering how can I set a deep key as index (`_uidFieldName`), in this case I want use the `userId` that is inside the `login` key
```js
let data = [
    {
        "name": "Melissa Smith",
        "email": "melissa.allen@example.com",
        "login": {
            "userId": 2562,
            "username": "heavycat937"
        }
    },
    {
        "name": "Jhon Smith",
        "email": "jhon.allen@example.com",
        "login": {
            "userId": 54213,
            "username": "jhon123"
        }
    }
]

```
in your example you use `isbn` which is key that is in the root of the object that's why my question.

Thanks

**Comment by bvaughn** [comment]
Thank you.

This actually was not supported before you asked, but I released 1.4.0 this evening which adds support. Instead of passing `Search` a string UID- pass it an array. In your case:

```js
const search = new Search(['login', 'userId']);
```
