### ISSUE TITLE
Only ever getting one result...

### ISSUE THREAD

**Issue by KyleAMathews** [bvaughn/js-search#34]
No idea what I'm doing wrong. Please send help :-)

On 1.4.0.

Setup looks like:

```js
const JsSearch = require('js-search')

const search = new JsSearch.Search()
search.addIndex('title')
search.addIndex('body')

search.addDocuments(posts) // There's about 2000 posts there.

// Regardless of what I search for, it returns just one result.
// The results are sensible and seem accurate and come from any of the documents
// but there's always just one.
search.search('a')

**Comment by bvaughn** [comment]
Haha, hey Kyle. How's it going?

Could I see at least a sample of your `posts` data?

**Comment by KyleAMathews** [comment]
Doing well, doing well thanks :-) Yourself?

So... it's from my journal so I can't show too much but here's a random entry that I'm not entirely sure where I was going with it but isn't super private so anyways each post has a body and title where the body is an excerpt from what I wrote capped at I think 600 characters.

```js
{
  body: "Philosopher William James once wrote that mental life is controlled by noticing. Climbing out of the sea and onto the windy beach, my skin purple and my mind in a reverie provoked by shock, I find myself thinking of a checklist Wozniak wrote a few years ago describing how to become a genius. His advice was straightforward yet strangely terrible: You must clarify your goals, gain knowledge through spaced repetition, preserve health, work steadily, minimize stress, refuse interruption, and never resist sleep when tired. This should lead to radically improved intelligence and creativity. The only..."
  title: "Recipe for becoming a genius"
}
```

**Comment by bvaughn** [comment]
Glad to hear. I'm good, thanks! 😄

You forgot to specify a UID field (as a constructor param). (Actually from the looks of your sample post, your data may not have such a field?)

**Comment by bvaughn** [comment]
```js
const JsSearch = require('js-search')

const posts = [
  {
    id: 1,
    body: "First book",
    title: "Book 1"
  },
  {
    id: 2,
    body: "Second book",
    title: "Book 2"
  },
  {
    id: 3,
    body: "Third book",
    title: "Book 3"
  }
]

const search = new JsSearch.Search('id')
search.addIndex('title')
search.addIndex('body')

search.addDocuments(posts);
search.search('book')
```

**Comment by KyleAMathews** [comment]
Ooo... it's working! Thanks! Super fast & nice.

Yeah, my data *has* an ID but I didn't think about how the search indexer would need an ID. Added that in and things are good.

Perhaps js-search could just auto-add ids if one isn't added? Or do you support updating documents so need ids to overwrite old documents with new documents?

Perhaps it should throw an error if you don't pass in the UID argument?

**Comment by bvaughn** [comment]
Sweet! Thanks!

Yeah I should definitely throw an error if you omit that param. It's pretty
important.

By the way, if you're using all default search settings, you might want to
consider js-worker-search. Same API but the index runs in a web worker
(when available) so it's faster still.

**Comment by KyleAMathews** [comment]
Does it just work with webpack?

**Comment by bvaughn** [comment]
It should. Uses the worker loader if workers are acceptable on the current
browser. (It's what redux-search uses under​ the hood, if you're interested
in an example integration.)

**Comment by KyleAMathews** [comment]
Cool! Will try this in the morning! (and will close this issue now)

**Comment by bvaughn** [comment]
FYI v1.4.2 throws if you omit this parameter 😉
