### ISSUE TITLE
Pick most important terms at build time so ship less data to browser

### ISSUE THREAD

**Issue by KyleAMathews** [bvaughn/js-search#35]
Working on adding search to my journal which has some ~2000 posts. Search performance is great but I am a bit concerned about how much data I have to ship to the browser. I'm already shipping just an excerpt of each post but even with that the JSON file ends up around ~600kb gzipped.

One idea would be to just ship the title plus short excerpt of each post to the browser along with some precomputed tokens for each post. So then each document would look like `{ id, title, body, tokens }` where tokens would be a string with each token separated by a space.

Does that seem reasonable? If so, is it easy to with your implementation to feed a document in and get out the top say 15 tokens? If not, this package seems to have something for this https://www.npmjs.com/package/natural.

**Comment by bvaughn** [comment]
Correct me if I'm misunderstanding you, Kyle- but if you're already doing the work of splitting out the `tokens` bit, couldn't you just build the local search index using `tokens` only? (or perhaps `tokens` _plus_ `title`, since you'll be sending the titles anyway?)

**Comment by bvaughn** [comment]
> If so, is it easy to with your implementation to feed a document in and get out the top say 15 tokens?

No. This sounds similar to my tf-idf index, but that wasn't created to consume data and spit out a ranking of tokens. Rather to rank search results by their tokens.

**Comment by KyleAMathews** [comment]
>but if you're already doing the work of splitting out the tokens bit, couldn't you just build the local search index using tokens only?

Yeah totally, I just wanted the excerpt for building a nice search results page :-)

Cool! Will try this then.

**Comment by bvaughn** [comment]
Cool!

Assuming you split the "interesting" tokens out server-side- which you should, to avoid needing to send the full data down for the search lib to process- you should be able to use:
```js
const { Search } = require('js-search');

const search = new Search('id');
search.addIndex('title');
search.addIndex('tokens');
```
