### ISSUE TITLE
Explain how to switch index strategies in the documentation

### ISSUE THREAD

**Issue by JobLeonard** [bvaughn/js-search#38]
Hey, just a suggestion.

I came here from [`react-select-fast-filter-options`](https://github.com/bvaughn/react-select-fast-filter-options#configuration-options), specifically the part in the documentation about configuration options.

It mentions that I can change from `AllSubstringsIndexStrategy` to another - in my case, I want to search by prefix only, so [`PrefixIndexStrategy`](https://github.com/bvaughn/js-search/blob/master/source/IndexStrategy/PrefixIndexStrategy.js). 

Now, [how to use those options is explained over at `react-select-fast-filter-options`](https://github.com/bvaughn/react-select-fast-filter-options#advanced-configuration), so I can figure it out, but I noticed it is not here in the documentation of `js-search`. That seems a bit odd to me, and perhaps confusing for anyone who comes to this library from somewhere else.

**Comment by bvaughn** [comment]
Agreed, the docs here could be much better. Would you be interested in helping? 😄

**Comment by JobLeonard** [comment]
Hahaha, I don't feel like I understand the library nearly well enough for that! But isn't "half" of it already written in the other repo?

**Comment by wuweiweiwu** [comment]
@bvaughn If this is still open I'd like to take it :)

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by bvaughn** [comment]
Documentation updated via #54. Thanks @wuweiweiwu!
