### ISSUE TITLE
Thanks!! And - sharing example code?

### ISSUE THREAD

**Issue by fiona-manzella** [bvaughn/js-search#39]
Found this after implementing react-virtualized which is great so far, thank you!
I'm running into some issues with getting js-search up and running on some tables in my app...your example at http://bvaughn.github.io/js-search/ looks really great but I was wondering if you'd be willing to share the code like in the react-virtualized repo examples, for reference?

**Comment by bvaughn** [comment]
Thanks! 😄

The code is shared in GitHub, on the `gh-pages` branch ([here](https://github.com/bvaughn/js-search/blob/gh-pages/script.js)). There's just very little of it in the demo.

Hope it's helpful!

**Comment by fiona-manzella** [comment]
Ahh gotcha! Ok that makes more sense. Thank you!!
