### ISSUE TITLE
Allow uidFieldName to be a nested property

### ISSUE THREAD

**Issue by johannes-z** [bvaughn/js-search#40]
Consider having an object like this:

```json
{
  "title": "Testobject #1",
  "date": "2017-06-20",
  "_metadata": {
    "id": "<some-GUID>"
  }
}
```

I want to be able to initialize the library like this: `new JsSearch.Search(['_metadata', 'id'])`, which doesn't work though. 

Also, compound `uidFieldName` could be helpful, f.e. `new JsSearch.Search('title', 'date')`, so the value for the `uidFieldName` would be something like this: `Testobject #1 - 2017-06-20`.

This would be very helpful, if you don't have a single unique property on the json object.

**Comment by bvaughn** [comment]
`uidFieldName` can be a nested value (see [here](https://github.com/bvaughn/js-search/blob/4eca3b8c6ab8000b1ca1aafc3253df59f6842c2a/source/Search.js#L178-L182) and [here](https://github.com/bvaughn/js-search/blob/4eca3b8c6ab8000b1ca1aafc3253df59f6842c2a/source/Search.test.js#L125-L154)). The docs probably do a poor job of pointing this out, in which case I'd welcome PRs to improve them.

I don't think a compound field name, as you describe, is something I want to support. If you'd like to submit a PR though I'd be happy to review it and give it consideration.
