### ISSUE TITLE
Support for accent-folding

### ISSUE THREAD

**Issue by davidfateh** [bvaughn/js-search#41]
Hello! I was wondering if there were any plans to add support for [accent-folding](https://alistapart.com/article/accent-folding-for-auto-complete). If not, it might be something I'd be interested in tackling.

**Comment by bvaughn** [comment]
This should already be possible using the [`Sanitizer` interface](https://github.com/bvaughn/js-search/blob/master/source/Sanitizer/Sanitizer.js).

For example, borrowing from the page you linked to, if you index the following set of names with js-search:
* Fulanito López
* Erik Lørgensen
* Lorena Smith
* James Lö

Using the default `Sanitizer` (`LowerCaseSanitizer`) searching for "o" would only return "Lorena Smith". But if your sanitizer converted "ó", "ø", and "ö" to "o" during the indexing process then searching for "o" would match all 4 records.

If you'd be interested in contributing a sanitizer that handles accent folding, I'd be happy to add it to the library. This should get you started:

```js
const ACCENT_MAP = {
  'ó': 'o',
  'ø': 'o',
  'ö': 'u'
  // Other characters here....
};

class AccentFoldingSanitizer {
  sanitize(text) {
    if (!text) {
      return '';
    } else {
      let sanitized = '';

      for (let i = 0; i < text.length; i++) {
        const char = text[i];

        sanitized += ACCENT_MAP.hasOwnProperty(char) ? ACCENT_MAP[char] : char;
      }

      return sanitized;
    }
  }
};
```

**Comment by bvaughn** [comment]
I _think_ this issue can be closed without further action- but let's talk more (or feel free to submit a PR) if you'd like 👍
