### ISSUE TITLE
UTF8 Support ?

### ISSUE THREAD

**Issue by AymanElarian** [bvaughn/js-search#43]
hello how can i search with arabic letters , search only get results with numbers or english letters ?

**Comment by bvaughn** [comment]
Hello! 😄 

The default implementation of [`Tokenizer`](https://github.com/bvaughn/js-search/blob/master/source/Tokenizer/Tokenizer.js) used by `js-search` is [`SimpleTokenizer`](https://github.com/bvaughn/js-search/blob/master/source/Tokenizer/SimpleTokenizer.js) which doesn't support Arabic letters. However, you can provide an alternate tokenizer implementation and js-search should work fine for you. For example:

```js
var REGEX = /\s+/; // Split on spaces
const tokenizer = {
  tokenize(text) {
    return text
      .split(REGEX)
      .filter(
        (text) => text // Filter empty tokens
      );
  }
}
const A = {id: 'A', text: 'لعربی مجهز بالمقام'}
const B = {id: 'B', text: 'موسیقی العربی'}

var search = new JsSearch.Search('id');
search.tokenizer = tokenizer;
search.addIndex('text');

search.addDocuments([A, B]);

search.search('م');
```

If you'd be interested in contributing an Arabic tokenizer as a PR I'd love to merge it into js-search so others can use it by default!

**Comment by AymanElarian** [comment]
@bvaughn thanks for your plugin and for your nice explanations ,
 i will be back with arabic once we have done with it  , right now your tokenizer working very good with me  ,<3 with love from egypt

**Comment by AymanElarian** [comment]
@sallyakl please follow this issue

**Comment by bvaughn** [comment]
I'm going to close this issue for now due to inactivity.

Still happy to review a PR for this though!

**Comment by omarkhaled11** [comment]
hello @bvaughn, I checked the regex you use for the simple tokenizer, I am not so good with regex but do you just need to add the first and last Arabic letters to make it split by letter? 
like next to a-z used here `var REGEX = /[^a-zа-яё0-9\-']+/i;` adding the (a-z) of Arabic letters would achieve similar results?

**Comment by bvaughn** [comment]
Maybe! I don't know Arabic so I can't say with authority whether that would work or not. 😅

**Comment by omarkhaled11** [comment]
guess what, it actually worked :) I tested adding this regex with the tokenizer `var REGEX = /[^a-zء-يа-яё0-9\-']+|/i` and it works and searches throughout the whole string like english characters, I can make a pull request for this, do you want me to update the regex var in SimpleTokenizer.js? or add a custom one?

**Comment by bvaughn** [comment]
> do you want me to update the regex var in SimpleTokenizer.js

I don't know what this would do to performance, so not unless you tested a lot of cases and ensured that it didn't negatively impact perf.

**Comment by omarkhaled11** [comment]
I have tested a lot of cases searching for different characters, all seemed working pretty well for both Arabic, English and numbers , but I have only tested with 100 records
