### ISSUE TITLE
Search by nested array

### ISSUE THREAD

**Issue by mvovchak** [bvaughn/js-search#47]
Hi! Is there a possibility to search nested array value like that?

```
array = [
{
   name: "Foo",
   subArray: [
      {
          subName: "Bar"
       }
    ]
}
];

search.addIndex("name");
search.addIndex("subArray[].subName");

search.addDocuments(array);
```

I could not find any documentation on how to do it.

**Comment by bvaughn** [comment]
The [overview docs](https://github.com/bvaughn/js-search#overview) kind of hint at this with the following snippet:
```js
var search = new JsSearch.Search('isbn');
search.addIndex('title');
search.addIndex(['author', 'name']); // This is a nested field
search.addIndex('tags');
```

It wasn't really meant to work with an array though, but you _could_ do something like:
```js
search.addIndex(["subArray", 0, "subName"]);
```

If you'd like to see better array support added (eg `["subArray", "[]", "subName"]`) you could put together a PR? 😄

**Comment by mvovchak** [comment]
Great, thanks.  I'll see if I can PR this next week

**Comment by oreporan** [comment]
Was this PR ever made?

**Comment by ziaulrehman40** [comment]
The solution suggested only works for arrays with single element/object.
