### ISSUE TITLE
How to create an index from a node app?

### ISSUE THREAD

**Issue by samdutton** [bvaughn/js-search#48]
Apologies if I'm missed something obvious, and I know this isn't really an 'issue', but I'm struggling to work out how to create an index from a Node app.

I've tried this:

```
  // documents is an array of objects, each with a name, title and description
  var search = new jsSearch.Search('name');
  search.addIndex('title');
  search.addIndex('description');
  search.addDocuments(documents);
  // make use of JSON.stringify(search);
```

I've also noticed that the benchmark code is somewhat different from the README code  — tried that as well.

**Comment by bvaughn** [comment]
Yeah, this isn't really fit for a GitHub issue. 😄 Probably better to ask on StackOverflow, and be sure to include information about what actually goes wrong. (I don't really understand what isn't working for you, based on this brief description.)

**Comment by samdutton** [comment]
OK — fair point :). I've posted a question [here](https://stackoverflow.com/questions/46454431/build-an-index-in-a-node-app-using-js-search).
