### ISSUE TITLE
Cannot be loaded by Node.js (module is set up improperly)

### ISSUE THREAD

**Issue by scommisso** [bvaughn/js-search#5]
The package.json should point to the distribution code (currently points to a file that does not exist).

**Comment by bvaughn** [comment]
Sorry for oversight (pointing to a file that doesn't exist). I see you posted a PR for this. Thanks! :)

**Comment by bvaughn** [comment]
I released your PR as version 1.2.1.

Interestingly enough though, when I run `npm run build` I get a significantly different `dist/js-search.js.map` file than the one in your PR. Any thoughts? (Did you do anything different to generate the one you included?)
