### ISSUE TITLE
The js-search doesn't  compatibility with Persian language

### ISSUE THREAD

**Issue by engmmrj** [bvaughn/js-search#51]
I have a site that it is Persian language but the js-search doesn't compatibility with Persian language and doesn't result when i have search any string

**Comment by bvaughn** [comment]
The default implementation of [`Tokenizer`](https://github.com/bvaughn/js-search/blob/master/source/Tokenizer/Tokenizer.js) used by `js-search` is [`SimpleTokenizer`](https://github.com/bvaughn/js-search/blob/master/source/Tokenizer/SimpleTokenizer.js) which targets Germanic languages.

However, you can provide an alternate tokenizer implementation and `js-search` should work fine for you. For example:

```js
var REGEX = /\s+/; // Split on spaces
const tokenizer = {
  tokenize(text) {
    return text
      .split(REGEX)
      .filter(
        (text) => text // Filter empty tokens
      );
  }
}
const A = {id: 'A', text: ' ایرانیان در آمریکا · خواهان یک ایران آزاد'}
const B = {id: 'B', text: 'حامی تمامی اقلیت ها · جدائی دین از دولت · جوامع'}

var search = new JsSearch.Search('id');
search.tokenizer = tokenizer;
search.addIndex('text');

search.addDocuments([A, B]);

search.search('دین'); // Should match B
```

If you'd be interested in contributing a Persian-friendly tokenizer as a PR I'd love to merge it into `js-search` so others can use it by default!

Note that this example tokenizer is super simplistic and presumably would have problems with punctuation. I'm not a native speaker so I'm not really qualified to create a tokenizer for it. However I wanted to provide a starting point for you in case you would be interested in contributing!
