### ISSUE TITLE
Can you document a more obvious thing for what to do with unicode text?

### ISSUE THREAD

**Issue by sontek** [bvaughn/js-search#53]
I'm not sure what is expected of me.  I basically have a list of names and I just want fuzzy text search on them.  I've implemented this like:

```
 const search = new JsSearch.Search(props.searchIndexKey);
            search.indexStrategy = new JsSearch.AllSubstringsIndexStrategy();

            for (let i = 0; i <= props.columns.length - 1; i++) {
                search.addIndex(props.columns[i].key);
            }

            if (this.props.searchMapping) {
                this.props.searchMapping.map((index) => {
                    search.addIndex(index);
                });
            }

            search.addDocuments(props.rows);
```

and then rows have names like:

```

阳 Eva Hamilton
鹏 成 Maynard
金凤 Abril Chapa
```

If I search for "Abril" it works, but if I search for "阳" it does not.   I read in the README it says I should implement a tokenizer but not sure what I should do here.  I just want it split on each character so that I can fuzzy match.

**Comment by bvaughn** [comment]
This basic question has been asked a few times already. 😄 Check out my previous answers:
* #43: UTF8 Support
* #50: Searching for special characters
* #51: The js-search doesn't compatibility with Persian language
* #26: Punctuation and special characters seems to cause issues
* #11: Add multiple language support to SimpleTokenizer

**Comment by sontek** [comment]
Haha, thanks!  I still think that you've had to answer it enough times that its worth documenting.  But that unblocks me

**Comment by bvaughn** [comment]
I've documented the interfaces already. Preventing (or pre-answering) all possible questions with documentation is impossible, and I have limited time for it anyway on side projects like this. 😄  That being said, PRs for all things (including documentation) are welcome.

**Comment by aprilmintacpineda** [comment]
```js
haystack.tokenizer = {
  tokenize (text) {
    return Array.from(text);
  }
};
```

I find that the tokenizer above works for both Chinese and English. I'm not sure for the other languages.

You might need to polyfill `Array.from`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill

Why not use `Array.split('')`? --> https://stackoverflow.com/questions/4547609/how-do-you-get-a-string-to-a-character-array-in-javascript/34717402#34717402
