### ISSUE TITLE
Get more than 1 result

### ISSUE THREAD

**Issue by thejams** [bvaughn/js-search#56]
Hello nice library, i have one doubt, this is how i'm working right now:

let search = new JsSearch.Search('isbn')
search.addIndex('firstName')
search.addIndex('lastName')
search.addIndex('publicId')
search.addDocuments(array)
let response = search.search(query)

Where array (search.addDocuments(array)) is an array of Users objects, and query is the "searchQuery", so if i receive an "James" as a query i have multiple users with the "firstName" James but the library only returns one.

So my question is, there is a configuration that i have to edit so the library returns more than one result ?

**Comment by bvaughn** [comment]
> So my question is, there is a configuration that i have to edit so the library returns more than one result ?

No. Search always returns an array.

There's no repro code/steps here so I can't really help beyond that. Sorry!

**Comment by siansell** [comment]
Just ran into the same thing. Looks like the `id` that `new JsSearch.Search(id)` is initialised with has to be a unique field in your array of objects. Docs could mention this.

Thanks for a useful lib.

**Comment by ttraenkler** [comment]
I'm having the same issue - @siansell is right, if the ids are not unique (which I incorrectly assumed in my case) only one element instead of an array is returned.
