### ISSUE TITLE
calling search with empty strings does not return entire array

### ISSUE THREAD

**Issue by r3wt** [bvaughn/js-search#57]
exactly as it states. i am using in react so i'm doing something like:

```jsx
{this.engine.search(this.state.search).map((v,i)=><FAQItem question={v.question} answer={v.answer} key={i} />)}
```

**Comment by bvaughn** [comment]
I can't fix or comment on a bug report without a repro case. If you want me to take a look, link me to a running example (e.g. CodeSandbox or Codepen) that shows the bug happening.

**Comment by r3wt** [comment]
its pretty simple, just call search with an empty string and returns an empty array.

**Comment by bvaughn** [comment]
An empty string isn't a valid search token. If you want all documents, just bypass search and use all documents.

**Comment by r3wt** [comment]
lol. couldn't you just return the array in such a case? wouldn't it make logical to do so, especially within the context of fp? I mean most people who are using your library are going to want to do so with the results. the change has no bearing on my codebase as i've already worked around this, just thought you might want to consider changing this behavior as it would be a major buff for using the library. thanks.

**Comment by r3wt** [comment]
That's a good point. I suppose there are people who are wanting an empty array when their input field is empty. at any rate, i think there are likely to be an equal amount of people who want to show everything and only use their input field to narrow down the results. so, perhaps as a compromise there could be a note about passing empty strings to search added to the readme?

**Comment by bvaughn** [comment]
I can see both sides of this.

If you want the full data set, it seems slightly preferable to skip search entirely and just use the entire data set. (Then again, the same argument could be made in reverse I suppose.)

Any interest in updating the README? 😄

**Comment by r3wt** [comment]
I suppose i could do that. What should it say though? I'm quite terrible with words haha

**Comment by bvaughn** [comment]
Writing docs is exhausting. I don't know. Take a stab at it and I'll make suggestions or tweaks on the PR!

**Comment by Floriferous** [comment]
To me the behaviour suggested by @r3wt would be preferred as well. You even did it like that in your demo!
http://bvaughn.github.io/js-search/
