### ISSUE TITLE
Remove or Delete Documents

### ISSUE THREAD

**Issue by knpwrs** [bvaughn/js-search#58]
Is it possible to remove/delete documents from an index or would one have to recreate the entire search index?

**Comment by bvaughn** [comment]
Because of the way the index is created/stored, removing documents is not
supported. You would need to either recreate the index or post-filter
"deleted" documents.

>

**Comment by knpwrs** [comment]
Got it, thanks!

**Comment by DeanKamali** [comment]
Sorry, I need more info on this, How can I re-create the index? I'm only seeing addIndex in the docs? I couldn't find example on post-filter either : /

**Comment by bvaughn** [comment]
> Sorry, I need more info on this, How can I re-create the index

The same way you created it initially. I literally meant that you'd have to create a new one. The API does not support removing indexed items.

> I couldn't find example on post-filter either.

I'm saying that if you didn't want to recreate the index when an item was deleted, you'd have to filter the list of result IDs to remove any deleted items. (Which means you'd need to maintain a list of deleted ids yourself.)

**Comment by DeanKamali** [comment]
@bvaughn, got it! thanks for your response.
