### ISSUE TITLE
Serialize Index

### ISSUE THREAD

**Issue by hipstersmoothie** [bvaughn/js-search#60]
I uses `lunr`. I have an app that:

1. Creates Search index -> [serializes it](https://lunrjs.com/guides/index_prebuilding.html#serialization)
2. Bundles Code Into front end app
3. Front end app loads the search index for searches

Is there the ability to serialize the search index created by `js-search`?

**Comment by bvaughn** [comment]
No, although it was discussed a bit in issue #55. I have done some initial experimentation with it, but parsing was always slow and I just haven't had time to make it faster.

If serializing the index is important for your app/use case, you should probably stick with Lunr for now. 😄
