### ISSUE TITLE
Search values that are part of deeper list

### ISSUE THREAD

**Issue by khibma** [bvaughn/js-search#61]
Hello, Similar to issue #32 -- is it possible to search for values part of a deeper list?
I'd like to be able to search on `name` and `alias` values inside a list of `fields`

thanks!
eg.

```
{
    "data": [
     {"name": "roads",
	"type": "FeatureClass",
	"featureType": "Simple",
	"shapeType": "Polygon",
	"fields": [{
		"name": "OBJECTID",
		"alias": "Object ID",
		"type": "OID"
	}, {
		"name": "GLOBALID",
		"alias": "Global ID",
		"type": "GlobalID"
	}, {
		"name": "lat",
		"alias": "latitude",
		"type": "float"
	}]
}]}
```

**Comment by bvaughn** [comment]
No. This is not supported, and I don't realistically have intentions (time) to add it. Sorry! 🙇
