### ISSUE TITLE
TokenHighlighter

### ISSUE THREAD

**Issue by ljm42** [bvaughn/js-search#62]
Hi, I am using js-search with stemming, and I really want to highlight the results with < mark ></ mark >.  I see that there is a TokenHighlighter class, do you have any tips on how to use it?  Thanks!

**Comment by bvaughn** [comment]
I kind of forgot that utility even existed... 😄 

You can see some examples of its use [in its unit test](https://github.com/bvaughn/js-search/blob/master/source/TokenHighlighter.test.js). Basically this:
```js
const highlighter = new TokenHighlighter();
const highlightedText = highlighter.highlight(textToSearch, arrayOfSearchWords);
```

Here's an example Code Sandbox: https://codesandbox.io/s/42r3yw8pv7

**Comment by bvaughn** [comment]
Yeah, to be honest I don't even remember why I wrote the `TokenHighlighter` or what use case I had in mind. 😅
