### ISSUE TITLE
None-English search content support. 

### ISSUE THREAD

**Issue by jianhua1982** [bvaughn/js-search#66]
How to config if search content is none-English, such as Chinese? Does it support? Thanks.

**Comment by bvaughn** [comment]
This basic question has been asked a few times already. 😄 Check out my previous answers:
* #51: The js-search doesn't compatibility with Persian language
* #50: Searching for special characters
* #43: UTF8 Support
* #26: Punctuation and special characters seems to cause issues
* #11: Add multiple language support to SimpleTokenizer
