### ISSUE TITLE
 umlauts not recognized... any suggestions?

### ISSUE THREAD

**Issue by MikeBroders** [bvaughn/js-search#71]
i have issues with umlauts like ä, ü, ö, in search term filtering...

it seems that they are just striped out and not being recognized.

do you have any suggestion how to handle this?

**Comment by bvaughn** [comment]
This question has been asked a few times already. Check out my previous answers:
* #66: None-English search content support.
* #51: The js-search doesn't compatibility with Persian language
* #50: Searching for special characters
* #43: UTF8 Support
* #26: Punctuation and special characters seems to cause issues
* #11: Add multiple language support to SimpleTokenizer

**Comment by MikeBroders** [comment]
thanks a lot… that should help.
