### ISSUE TITLE
1000+ row search

### ISSUE THREAD

**Issue by knwin** [bvaughn/js-search#72]
It become a bit slow at first one or two letter search when I have a json data with more than ten thousand rows. (sorry not one thousand plus rows)
How can it make faster?

**Comment by bvaughn** [comment]
Past a certain point, you can't. If it needs to index and search a ton of documents, the time will increase with the more documents that are added.

I suggest taking a look at [js-worker-search](https://github.com/bvaughn/js-worker-search) instead as a possible alternative. Less flexible API but should perform better.
