### ISSUE TITLE
Is there a way to change the search to be 2 columns?

### ISSUE THREAD

**Issue by sontek** [bvaughn/js-search#74]
Hello, I have table:

```
first name | last name | email_address           | confirmation number
------------------------------------------------------------------------
John       |  Anderson | john_anderson@gmail.com | abc123
```

I would like to have the search exactly match a combination of first and last name, or an exact match of just email, or just confirmation number.

so "John Anderson" would match but "John A" would not.   "abc123" would also match

**Comment by bvaughn** [comment]
Are you just asking  for full word match  rather than subtring?

**Comment by sontek** [comment]
Yeah, basically.  I've tried creating a column like "full_name" and told it to do an ExactWordIndexStrategy, but it seems to still split on spaces and search on those.   So "John " still matches even though I only want it to match if it gets "John Anderson"

**Comment by sontek** [comment]
So my idea was to either:

Match whole words by creating a `full_name` column OR tell it to some how match exact for 2 columns combined.   Either strategy would work for me.  I'm basically looking for no fuzzy matching, just exact word matching for each index.

**Comment by bvaughn** [comment]
Seems like you would need to supply your own tokenizer to create the custom search tokens you're looking for.

**Comment by bvaughn** [comment]
There's no built in, out of the box support for this though :)

**Comment by sontek** [comment]
Hah, yeah.  Didn't even think of that.  I guess what I'm literally looking for is:

```
    search.tokenizer = {
      tokenize( text ) {
        return [text];
      }
    };
```

**Comment by bvaughn** [comment]
That sounds more like the exact word strategy. Sounds like you want something more custom, that's multi-column match. So rather than converting a string to tokens of string-subsets, you want to convert a document to tokens of column-combinations.

I _think_ this should be doable though :) good luck~
