### ISSUE TITLE
keyword "sécu" always return result but nothing contains "sécu" was indexed

### ISSUE THREAD

**Issue by alexis-puska** [bvaughn/js-search#75]
Hi, 
I user JsSearch to index some content to retrieve url page. In all environment "dev, ci, prod" the keyword search "sécu" return page content, not the same content for this 3 environment but its the same database that we fetcth the content to index with JsSearch. I have tryied to add this in stopKeywordMaps, but nothing is done, we retrieve some content with this keyword. Do you have any idea ? thx

**Comment by bvaughn** [comment]
Sorry, I can't help when there's no repro.

**Comment by alexis-puska** [comment]
This is a bug!
When you search a word with an accent éèê... the search query contains "s&eacute;cu" only "cu" is search inside the index and the result get more result instead of "sécu". We fix this by remove all accent inside the search query. I think that the char ';' create the problem

**Comment by bvaughn** [comment]
As I said right above, I don't investigate "bug" reports when there's no repro. If it's worth my time to spend looking into it, it's worth your time to spend creating a repro case that can be shared.

Before doing that, I suggest you also search other issues in this repo..

* #51: The js-search doesn't compatibility with Persian language
* #50: Searching for special characters
* #43: UTF8 Support
* #26: Punctuation and special characters seems to cause issues
* #11: Add multiple language support to SimpleTokenizer
