### ISSUE TITLE
Highlight match

### ISSUE THREAD

**Issue by oreporan** [bvaughn/js-search#76]
Hey, thanks for the useful library

I was wondering if its possible to add some callback capability on the found term.
In my search result I'd like to highlight (by wrapping with some `<span>`) the found term.

So maybe something like:

```js
const jsSearch = new JsSearch.Search('messages');
jsSearch.onMatch = (match) => `<span>${match}</span>`

....

const results = jsSearch.search('Great')

console.log(results)

 {
  isbn: '9781597226769',
  title: 'The <span>Great</span> Gatsby',
  author: {
    name: 'F. Scott Fitzgerald'
  },
  tags: ['book', 'inspirational']
};
```

**Comment by bvaughn** [comment]
This library does not do any visualization, only raw searching. I don't really have much interest in expanding its scope either. Sorry :smile:
