### ISSUE TITLE
Search Query data will be added more than once with re-rendering in React?

### ISSUE THREAD

**Issue by kvin97** [bvaughn/js-search#79]
In React when I use js-search, json objects that I've given added more than once in search module.
I created a new file for js-search setup and I'm using it in my component.
******************************************************************************************
import * as JsSearch from 'js-search';

const search = new JsSearch.Search('id');
search.addIndex('effectiveDate');
search.addIndex('opco');
search.addIndex('priceType');
search.addIndex('status');
search.addIndex('vendorGroupID');

export default search;
**********************************************************************************************
Now I'm using search.addDocument(data) in componentDidUpdate life cycle to give the 'data' array whenever the component updates. But data will be added more than once. For clarification following image taken with console.log(search).
![jsSearch](https://user-images.githubusercontent.com/53901190/65900149-ec621900-e3d2-11e9-8cff-e9dcac4bbfba.png)

Can anyone tell me how to solve this issue?

**Comment by DanPen** [comment]
Every time you import your specified module, it will create a new JS Search instance. You should export a function or class instead. Then, you should call that function (or create a class instance) only once.
