### ISSUE TITLE
Feature request: Is it possible to return which index(es) caused the document to be found?

### ISSUE THREAD

**Issue by DanPen** [bvaughn/js-search#80]
I'm using js-search to filter geographical places. Currently using three indices: `name` (string), `keywords` (array of strings), and `people` (array of strings).

I need to know whether or not `people` caused (or helped) the result to be found.

Is there any way this can be implemented, or is already implemented? If not, what would be the best way that I can implement this?

**Comment by bvaughn** [comment]
No, this is not supported. Sorry!
