### ISSUE TITLE
Search only returns one result

### ISSUE THREAD

**Issue by jf-home** [bvaughn/js-search#82]
Hi, 

I have created a project which is searching over markdown content from one of my sample sites: 

     https://condescending-snyder-8ead2e.netlify.com/search/searchIndex.json 

Unfortunately, the search only ever returns one result when, in some cases, it should return several.  I suspect this may be down to my JSON structure - however - I've hit a brick wall and would appreciate any help that you may be able to provide.  

My project is available here: 

     https://github.com/jf-home/js-search

Thanks in advance!

**Comment by hugofabricio** [comment]
Hi @jf-home , change node.id to id of your search index object. 

```new JsSearch.Search("node.id")```

**Comment by jf-home** [comment]
> 
> 
> Hi @jf-home , change node.id to id of your search index object.
> 
> `new JsSearch.Search("node.id")`

@hugofabricio - Spot on!  Thank you!  A quick change from 
     JsSearch.Search("node.id")
 - to - 
     JsSearch.Search(["node", "id"])
...sorted the issue out.  

Really appreciate you help.   Thanks again.
