### ISSUE TITLE
Language support?

### ISSUE THREAD

**Issue by urtti** [bvaughn/js-search#87]
Hey, what is the support for different languages in js-search? One of my projects is having trouble getting the correct search results with Korean. Is this a configuration issue on my part or does js-search only support English characters? 

For English letters it works fantastically so thank you for this very nice piece of software!

**Comment by urtti** [comment]
Not issue anymore, rolled my own simple search.

**Comment by astroplex** [comment]
How to handle korean?

@urtti

**Comment by urtti** [comment]
> How to handle korean?
> 
> @urtti

Hey, so as mentioned above, I decided against using js-search and just did my own very simple string comparison that worked with Korean characters as well.
